
# Automatically generated by /home/kevin/Documents/cpsc-120-prompt-lab-02/.action/ccsrcutilities.py on 2023-09-07 21:10:35

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f .Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

